name: Web E2E Tests

on: 
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npm run cy:run
        continue-on-error: true

      - name: Generate Allure Report
        if: always()
        run: npm run allure:generate

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 5